// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: alerts.proto

package alertspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertDefPriority int32

const (
	AlertDefPriority_ALERT_DEF_PRIORITY_P5_OR_UNSPECIFIED AlertDefPriority = 0
	AlertDefPriority_ALERT_DEF_PRIORITY_P1                AlertDefPriority = 1
	AlertDefPriority_ALERT_DEF_PRIORITY_P2                AlertDefPriority = 2
	AlertDefPriority_ALERT_DEF_PRIORITY_P3                AlertDefPriority = 3
	AlertDefPriority_ALERT_DEF_PRIORITY_P4                AlertDefPriority = 4
	AlertDefPriority_ALERT_DEF_PRIORITY_P5                AlertDefPriority = 5
)

// Enum value maps for AlertDefPriority.
var (
	AlertDefPriority_name = map[int32]string{
		0: "ALERT_DEF_PRIORITY_P5_OR_UNSPECIFIED",
		1: "ALERT_DEF_PRIORITY_P1",
		2: "ALERT_DEF_PRIORITY_P2",
		3: "ALERT_DEF_PRIORITY_P3",
		4: "ALERT_DEF_PRIORITY_P4",
		5: "ALERT_DEF_PRIORITY_P5",
	}
	AlertDefPriority_value = map[string]int32{
		"ALERT_DEF_PRIORITY_P5_OR_UNSPECIFIED": 0,
		"ALERT_DEF_PRIORITY_P1":                1,
		"ALERT_DEF_PRIORITY_P2":                2,
		"ALERT_DEF_PRIORITY_P3":                3,
		"ALERT_DEF_PRIORITY_P4":                4,
		"ALERT_DEF_PRIORITY_P5":                5,
	}
)

func (x AlertDefPriority) Enum() *AlertDefPriority {
	p := new(AlertDefPriority)
	*p = x
	return p
}

func (x AlertDefPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertDefPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[0].Descriptor()
}

func (AlertDefPriority) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[0]
}

func (x AlertDefPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertDefPriority.Descriptor instead.
func (AlertDefPriority) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

type AlertDefType int32

const (
	AlertDefType_ALERT_DEF_TYPE_LOGS_IMMEDIATE_OR_UNSPECIFIED AlertDefType = 0
	AlertDefType_ALERT_DEF_TYPE_LOGS_THRESHOLD                AlertDefType = 1
	AlertDefType_ALERT_DEF_TYPE_LOGS_RATIO_THRESHOLD          AlertDefType = 2
	AlertDefType_ALERT_DEF_TYPE_LOGS_TIME_RELATIVE_THRESHOLD  AlertDefType = 3
	AlertDefType_ALERT_DEF_TYPE_LOGS_ANOMALY                  AlertDefType = 4
	AlertDefType_ALERT_DEF_TYPE_LOGS_NEW_VALUE                AlertDefType = 5
	AlertDefType_ALERT_DEF_TYPE_LOGS_UNIQUE_COUNT             AlertDefType = 6
	AlertDefType_ALERT_DEF_TYPE_METRIC_THRESHOLD              AlertDefType = 7
	AlertDefType_ALERT_DEF_TYPE_METRIC_ANOMALY                AlertDefType = 8
	AlertDefType_ALERT_DEF_TYPE_TRACING_IMMEDIATE             AlertDefType = 9
	AlertDefType_ALERT_DEF_TYPE_TRACING_THRESHOLD             AlertDefType = 10
	AlertDefType_ALERT_DEF_TYPE_FLOW                          AlertDefType = 11
)

// Enum value maps for AlertDefType.
var (
	AlertDefType_name = map[int32]string{
		0:  "ALERT_DEF_TYPE_LOGS_IMMEDIATE_OR_UNSPECIFIED",
		1:  "ALERT_DEF_TYPE_LOGS_THRESHOLD",
		2:  "ALERT_DEF_TYPE_LOGS_RATIO_THRESHOLD",
		3:  "ALERT_DEF_TYPE_LOGS_TIME_RELATIVE_THRESHOLD",
		4:  "ALERT_DEF_TYPE_LOGS_ANOMALY",
		5:  "ALERT_DEF_TYPE_LOGS_NEW_VALUE",
		6:  "ALERT_DEF_TYPE_LOGS_UNIQUE_COUNT",
		7:  "ALERT_DEF_TYPE_METRIC_THRESHOLD",
		8:  "ALERT_DEF_TYPE_METRIC_ANOMALY",
		9:  "ALERT_DEF_TYPE_TRACING_IMMEDIATE",
		10: "ALERT_DEF_TYPE_TRACING_THRESHOLD",
		11: "ALERT_DEF_TYPE_FLOW",
	}
	AlertDefType_value = map[string]int32{
		"ALERT_DEF_TYPE_LOGS_IMMEDIATE_OR_UNSPECIFIED": 0,
		"ALERT_DEF_TYPE_LOGS_THRESHOLD":                1,
		"ALERT_DEF_TYPE_LOGS_RATIO_THRESHOLD":          2,
		"ALERT_DEF_TYPE_LOGS_TIME_RELATIVE_THRESHOLD":  3,
		"ALERT_DEF_TYPE_LOGS_ANOMALY":                  4,
		"ALERT_DEF_TYPE_LOGS_NEW_VALUE":                5,
		"ALERT_DEF_TYPE_LOGS_UNIQUE_COUNT":             6,
		"ALERT_DEF_TYPE_METRIC_THRESHOLD":              7,
		"ALERT_DEF_TYPE_METRIC_ANOMALY":                8,
		"ALERT_DEF_TYPE_TRACING_IMMEDIATE":             9,
		"ALERT_DEF_TYPE_TRACING_THRESHOLD":             10,
		"ALERT_DEF_TYPE_FLOW":                          11,
	}
)

func (x AlertDefType) Enum() *AlertDefType {
	p := new(AlertDefType)
	*p = x
	return p
}

func (x AlertDefType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertDefType) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[1].Descriptor()
}

func (AlertDefType) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[1]
}

func (x AlertDefType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertDefType.Descriptor instead.
func (AlertDefType) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

type DayOfWeek int32

const (
	DayOfWeek_DAY_OF_WEEK_MONDAY_OR_UNSPECIFIED DayOfWeek = 0
	DayOfWeek_DAY_OF_WEEK_TUESDAY               DayOfWeek = 1
	DayOfWeek_DAY_OF_WEEK_WEDNESDAY             DayOfWeek = 2
	DayOfWeek_DAY_OF_WEEK_THURSDAY              DayOfWeek = 3
	DayOfWeek_DAY_OF_WEEK_FRIDAY                DayOfWeek = 4
	DayOfWeek_DAY_OF_WEEK_SATURDAY              DayOfWeek = 5
	DayOfWeek_DAY_OF_WEEK_SUNDAY                DayOfWeek = 6
)

// Enum value maps for DayOfWeek.
var (
	DayOfWeek_name = map[int32]string{
		0: "DAY_OF_WEEK_MONDAY_OR_UNSPECIFIED",
		1: "DAY_OF_WEEK_TUESDAY",
		2: "DAY_OF_WEEK_WEDNESDAY",
		3: "DAY_OF_WEEK_THURSDAY",
		4: "DAY_OF_WEEK_FRIDAY",
		5: "DAY_OF_WEEK_SATURDAY",
		6: "DAY_OF_WEEK_SUNDAY",
	}
	DayOfWeek_value = map[string]int32{
		"DAY_OF_WEEK_MONDAY_OR_UNSPECIFIED": 0,
		"DAY_OF_WEEK_TUESDAY":               1,
		"DAY_OF_WEEK_WEDNESDAY":             2,
		"DAY_OF_WEEK_THURSDAY":              3,
		"DAY_OF_WEEK_FRIDAY":                4,
		"DAY_OF_WEEK_SATURDAY":              5,
		"DAY_OF_WEEK_SUNDAY":                6,
	}
)

func (x DayOfWeek) Enum() *DayOfWeek {
	p := new(DayOfWeek)
	*p = x
	return p
}

func (x DayOfWeek) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DayOfWeek) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[2].Descriptor()
}

func (DayOfWeek) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[2]
}

func (x DayOfWeek) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DayOfWeek.Descriptor instead.
func (DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

// Wire-compatible with google.protobuf.StringValue but uses bytes to
// avoid proto3 UTF-8 enforcement on data from Coralogix.
type StrVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrVal) Reset() {
	*x = StrVal{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrVal) ProtoMessage() {}

func (x *StrVal) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrVal.ProtoReflect.Descriptor instead.
func (*StrVal) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *StrVal) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListAlertDefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertDefsRequest) Reset() {
	*x = ListAlertDefsRequest{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertDefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertDefsRequest) ProtoMessage() {}

func (x *ListAlertDefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertDefsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertDefsRequest) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

type ListAlertDefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertDefs     []*AlertDef            `protobuf:"bytes,1,rep,name=alert_defs,json=alertDefs,proto3" json:"alert_defs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertDefsResponse) Reset() {
	*x = ListAlertDefsResponse{}
	mi := &file_alerts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertDefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertDefsResponse) ProtoMessage() {}

func (x *ListAlertDefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertDefsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertDefsResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertDefsResponse) GetAlertDefs() []*AlertDef {
	if x != nil {
		return x.AlertDefs
	}
	return nil
}

type GetAlertDefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *StrVal                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertDefRequest) Reset() {
	*x = GetAlertDefRequest{}
	mi := &file_alerts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertDefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertDefRequest) ProtoMessage() {}

func (x *GetAlertDefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertDefRequest.ProtoReflect.Descriptor instead.
func (*GetAlertDefRequest) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertDefRequest) GetId() *StrVal {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetAlertDefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertDef      *AlertDef              `protobuf:"bytes,1,opt,name=alert_def,json=alertDef,proto3" json:"alert_def,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertDefResponse) Reset() {
	*x = GetAlertDefResponse{}
	mi := &file_alerts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertDefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertDefResponse) ProtoMessage() {}

func (x *GetAlertDefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertDefResponse.ProtoReflect.Descriptor instead.
func (*GetAlertDefResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertDefResponse) GetAlertDef() *AlertDef {
	if x != nil {
		return x.AlertDef
	}
	return nil
}

type AlertDef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AlertDefProperties *AlertDefProperties    `protobuf:"bytes,1,opt,name=alert_def_properties,json=alertDefProperties,proto3" json:"alert_def_properties,omitempty"`
	Id                 *StrVal                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	AlertVersionId     *StrVal                `protobuf:"bytes,20,opt,name=alert_version_id,json=alertVersionId,proto3" json:"alert_version_id,omitempty"`
	CreatedTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	LastTriggeredTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_triggered_time,json=lastTriggeredTime,proto3" json:"last_triggered_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AlertDef) Reset() {
	*x = AlertDef{}
	mi := &file_alerts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertDef) ProtoMessage() {}

func (x *AlertDef) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertDef.ProtoReflect.Descriptor instead.
func (*AlertDef) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{5}
}

func (x *AlertDef) GetAlertDefProperties() *AlertDefProperties {
	if x != nil {
		return x.AlertDefProperties
	}
	return nil
}

func (x *AlertDef) GetId() *StrVal {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AlertDef) GetAlertVersionId() *StrVal {
	if x != nil {
		return x.AlertVersionId
	}
	return nil
}

func (x *AlertDef) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *AlertDef) GetUpdatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTime
	}
	return nil
}

func (x *AlertDef) GetLastTriggeredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTriggeredTime
	}
	return nil
}

type AlertDefProperties struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        *StrVal                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description *StrVal                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled     *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority    AlertDefPriority       `protobuf:"varint,4,opt,name=priority,proto3,enum=com.coralogixapis.alerts.v3.AlertDefPriority" json:"priority,omitempty"`
	// Types that are valid to be assigned to Schedule:
	//
	//	*AlertDefProperties_ActiveOn
	Schedule isAlertDefProperties_Schedule `protobuf_oneof:"schedule"`
	Type     AlertDefType                  `protobuf:"varint,6,opt,name=type,proto3,enum=com.coralogixapis.alerts.v3.AlertDefType" json:"type,omitempty"`
	// Types that are valid to be assigned to TypeDefinition:
	//
	//	*AlertDefProperties_LogsImmediate
	//	*AlertDefProperties_TracingImmediate
	//	*AlertDefProperties_LogsThreshold
	//	*AlertDefProperties_LogsRatioThreshold
	//	*AlertDefProperties_LogsTimeRelativeThreshold
	//	*AlertDefProperties_MetricThreshold
	//	*AlertDefProperties_TracingThreshold
	//	*AlertDefProperties_Flow
	//	*AlertDefProperties_LogsAnomaly
	//	*AlertDefProperties_MetricAnomaly
	//	*AlertDefProperties_LogsNewValue
	//	*AlertDefProperties_LogsUniqueCount
	TypeDefinition    isAlertDefProperties_TypeDefinition `protobuf_oneof:"type_definition"`
	GroupByKeys       []*StrVal                           `protobuf:"bytes,7,rep,name=group_by_keys,json=groupByKeys,proto3" json:"group_by_keys,omitempty"`
	IncidentsSettings *AlertDefIncidentSettings           `protobuf:"bytes,8,opt,name=incidents_settings,json=incidentsSettings,proto3" json:"incidents_settings,omitempty"`
	NotificationGroup *AlertDefNotificationGroup          `protobuf:"bytes,9,opt,name=notification_group,json=notificationGroup,proto3" json:"notification_group,omitempty"`
	EntityLabels      map[string][]byte                   `protobuf:"bytes,10,rep,name=entity_labels,json=entityLabels,proto3" json:"entity_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PhantomMode       *wrapperspb.BoolValue               `protobuf:"bytes,11,opt,name=phantom_mode,json=phantomMode,proto3" json:"phantom_mode,omitempty"`
	Deleted           *wrapperspb.BoolValue               `protobuf:"bytes,12,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlertDefProperties) Reset() {
	*x = AlertDefProperties{}
	mi := &file_alerts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertDefProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertDefProperties) ProtoMessage() {}

func (x *AlertDefProperties) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertDefProperties.ProtoReflect.Descriptor instead.
func (*AlertDefProperties) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{6}
}

func (x *AlertDefProperties) GetName() *StrVal {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *AlertDefProperties) GetDescription() *StrVal {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *AlertDefProperties) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *AlertDefProperties) GetPriority() AlertDefPriority {
	if x != nil {
		return x.Priority
	}
	return AlertDefPriority_ALERT_DEF_PRIORITY_P5_OR_UNSPECIFIED
}

func (x *AlertDefProperties) GetSchedule() isAlertDefProperties_Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *AlertDefProperties) GetActiveOn() *ActivitySchedule {
	if x != nil {
		if x, ok := x.Schedule.(*AlertDefProperties_ActiveOn); ok {
			return x.ActiveOn
		}
	}
	return nil
}

func (x *AlertDefProperties) GetType() AlertDefType {
	if x != nil {
		return x.Type
	}
	return AlertDefType_ALERT_DEF_TYPE_LOGS_IMMEDIATE_OR_UNSPECIFIED
}

func (x *AlertDefProperties) GetTypeDefinition() isAlertDefProperties_TypeDefinition {
	if x != nil {
		return x.TypeDefinition
	}
	return nil
}

func (x *AlertDefProperties) GetLogsImmediate() *LogsImmediateType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsImmediate); ok {
			return x.LogsImmediate
		}
	}
	return nil
}

func (x *AlertDefProperties) GetTracingImmediate() *TracingImmediateType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_TracingImmediate); ok {
			return x.TracingImmediate
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsThreshold() *LogsThresholdType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsThreshold); ok {
			return x.LogsThreshold
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsRatioThreshold() *LogsRatioThresholdType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsRatioThreshold); ok {
			return x.LogsRatioThreshold
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsTimeRelativeThreshold() *LogsTimeRelativeThresholdType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsTimeRelativeThreshold); ok {
			return x.LogsTimeRelativeThreshold
		}
	}
	return nil
}

func (x *AlertDefProperties) GetMetricThreshold() *MetricThresholdType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_MetricThreshold); ok {
			return x.MetricThreshold
		}
	}
	return nil
}

func (x *AlertDefProperties) GetTracingThreshold() *TracingThresholdType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_TracingThreshold); ok {
			return x.TracingThreshold
		}
	}
	return nil
}

func (x *AlertDefProperties) GetFlow() *FlowType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_Flow); ok {
			return x.Flow
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsAnomaly() *LogsAnomalyType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsAnomaly); ok {
			return x.LogsAnomaly
		}
	}
	return nil
}

func (x *AlertDefProperties) GetMetricAnomaly() *MetricAnomalyType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_MetricAnomaly); ok {
			return x.MetricAnomaly
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsNewValue() *LogsNewValueType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsNewValue); ok {
			return x.LogsNewValue
		}
	}
	return nil
}

func (x *AlertDefProperties) GetLogsUniqueCount() *LogsUniqueCountType {
	if x != nil {
		if x, ok := x.TypeDefinition.(*AlertDefProperties_LogsUniqueCount); ok {
			return x.LogsUniqueCount
		}
	}
	return nil
}

func (x *AlertDefProperties) GetGroupByKeys() []*StrVal {
	if x != nil {
		return x.GroupByKeys
	}
	return nil
}

func (x *AlertDefProperties) GetIncidentsSettings() *AlertDefIncidentSettings {
	if x != nil {
		return x.IncidentsSettings
	}
	return nil
}

func (x *AlertDefProperties) GetNotificationGroup() *AlertDefNotificationGroup {
	if x != nil {
		return x.NotificationGroup
	}
	return nil
}

func (x *AlertDefProperties) GetEntityLabels() map[string][]byte {
	if x != nil {
		return x.EntityLabels
	}
	return nil
}

func (x *AlertDefProperties) GetPhantomMode() *wrapperspb.BoolValue {
	if x != nil {
		return x.PhantomMode
	}
	return nil
}

func (x *AlertDefProperties) GetDeleted() *wrapperspb.BoolValue {
	if x != nil {
		return x.Deleted
	}
	return nil
}

type isAlertDefProperties_Schedule interface {
	isAlertDefProperties_Schedule()
}

type AlertDefProperties_ActiveOn struct {
	ActiveOn *ActivitySchedule `protobuf:"bytes,5,opt,name=active_on,json=activeOn,proto3,oneof"`
}

func (*AlertDefProperties_ActiveOn) isAlertDefProperties_Schedule() {}

type isAlertDefProperties_TypeDefinition interface {
	isAlertDefProperties_TypeDefinition()
}

type AlertDefProperties_LogsImmediate struct {
	LogsImmediate *LogsImmediateType `protobuf:"bytes,101,opt,name=logs_immediate,json=logsImmediate,proto3,oneof"`
}

type AlertDefProperties_TracingImmediate struct {
	TracingImmediate *TracingImmediateType `protobuf:"bytes,102,opt,name=tracing_immediate,json=tracingImmediate,proto3,oneof"`
}

type AlertDefProperties_LogsThreshold struct {
	LogsThreshold *LogsThresholdType `protobuf:"bytes,103,opt,name=logs_threshold,json=logsThreshold,proto3,oneof"`
}

type AlertDefProperties_LogsRatioThreshold struct {
	LogsRatioThreshold *LogsRatioThresholdType `protobuf:"bytes,104,opt,name=logs_ratio_threshold,json=logsRatioThreshold,proto3,oneof"`
}

type AlertDefProperties_LogsTimeRelativeThreshold struct {
	LogsTimeRelativeThreshold *LogsTimeRelativeThresholdType `protobuf:"bytes,105,opt,name=logs_time_relative_threshold,json=logsTimeRelativeThreshold,proto3,oneof"`
}

type AlertDefProperties_MetricThreshold struct {
	MetricThreshold *MetricThresholdType `protobuf:"bytes,106,opt,name=metric_threshold,json=metricThreshold,proto3,oneof"`
}

type AlertDefProperties_TracingThreshold struct {
	TracingThreshold *TracingThresholdType `protobuf:"bytes,107,opt,name=tracing_threshold,json=tracingThreshold,proto3,oneof"`
}

type AlertDefProperties_Flow struct {
	Flow *FlowType `protobuf:"bytes,108,opt,name=flow,proto3,oneof"`
}

type AlertDefProperties_LogsAnomaly struct {
	LogsAnomaly *LogsAnomalyType `protobuf:"bytes,109,opt,name=logs_anomaly,json=logsAnomaly,proto3,oneof"`
}

type AlertDefProperties_MetricAnomaly struct {
	MetricAnomaly *MetricAnomalyType `protobuf:"bytes,110,opt,name=metric_anomaly,json=metricAnomaly,proto3,oneof"`
}

type AlertDefProperties_LogsNewValue struct {
	LogsNewValue *LogsNewValueType `protobuf:"bytes,111,opt,name=logs_new_value,json=logsNewValue,proto3,oneof"`
}

type AlertDefProperties_LogsUniqueCount struct {
	LogsUniqueCount *LogsUniqueCountType `protobuf:"bytes,112,opt,name=logs_unique_count,json=logsUniqueCount,proto3,oneof"`
}

func (*AlertDefProperties_LogsImmediate) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_TracingImmediate) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsThreshold) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsRatioThreshold) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsTimeRelativeThreshold) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_MetricThreshold) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_TracingThreshold) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_Flow) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsAnomaly) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_MetricAnomaly) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsNewValue) isAlertDefProperties_TypeDefinition() {}

func (*AlertDefProperties_LogsUniqueCount) isAlertDefProperties_TypeDefinition() {}

type ActivitySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayOfWeek     []DayOfWeek            `protobuf:"varint,1,rep,packed,name=day_of_week,json=dayOfWeek,proto3,enum=com.coralogixapis.alerts.v3.DayOfWeek" json:"day_of_week,omitempty"`
	StartTime     *TimeOfDay             `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *TimeOfDay             `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySchedule) Reset() {
	*x = ActivitySchedule{}
	mi := &file_alerts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySchedule) ProtoMessage() {}

func (x *ActivitySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySchedule.ProtoReflect.Descriptor instead.
func (*ActivitySchedule) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{7}
}

func (x *ActivitySchedule) GetDayOfWeek() []DayOfWeek {
	if x != nil {
		return x.DayOfWeek
	}
	return nil
}

func (x *ActivitySchedule) GetStartTime() *TimeOfDay {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ActivitySchedule) GetEndTime() *TimeOfDay {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type TimeOfDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeOfDay) Reset() {
	*x = TimeOfDay{}
	mi := &file_alerts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeOfDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOfDay) ProtoMessage() {}

func (x *TimeOfDay) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOfDay.ProtoReflect.Descriptor instead.
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{8}
}

func (x *TimeOfDay) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *TimeOfDay) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type AlertDefIncidentSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyOn      *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=notify_on,json=notifyOn,proto3" json:"notify_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertDefIncidentSettings) Reset() {
	*x = AlertDefIncidentSettings{}
	mi := &file_alerts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertDefIncidentSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertDefIncidentSettings) ProtoMessage() {}

func (x *AlertDefIncidentSettings) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertDefIncidentSettings.ProtoReflect.Descriptor instead.
func (*AlertDefIncidentSettings) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{9}
}

func (x *AlertDefIncidentSettings) GetNotifyOn() *wrapperspb.Int32Value {
	if x != nil {
		return x.NotifyOn
	}
	return nil
}

type AlertDefNotificationGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupByFields []*StrVal              `protobuf:"bytes,1,rep,name=group_by_fields,json=groupByFields,proto3" json:"group_by_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertDefNotificationGroup) Reset() {
	*x = AlertDefNotificationGroup{}
	mi := &file_alerts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertDefNotificationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertDefNotificationGroup) ProtoMessage() {}

func (x *AlertDefNotificationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertDefNotificationGroup.ProtoReflect.Descriptor instead.
func (*AlertDefNotificationGroup) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{10}
}

func (x *AlertDefNotificationGroup) GetGroupByFields() []*StrVal {
	if x != nil {
		return x.GroupByFields
	}
	return nil
}

type LogsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LuceneFilter  *StrVal                `protobuf:"bytes,1,opt,name=lucene_filter,json=luceneFilter,proto3" json:"lucene_filter,omitempty"`
	AliasFilters  []*LogsFilterAlias     `protobuf:"bytes,2,rep,name=alias_filters,json=aliasFilters,proto3" json:"alias_filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsFilter) Reset() {
	*x = LogsFilter{}
	mi := &file_alerts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsFilter) ProtoMessage() {}

func (x *LogsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsFilter.ProtoReflect.Descriptor instead.
func (*LogsFilter) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{11}
}

func (x *LogsFilter) GetLuceneFilter() *StrVal {
	if x != nil {
		return x.LuceneFilter
	}
	return nil
}

func (x *LogsFilter) GetAliasFilters() []*LogsFilterAlias {
	if x != nil {
		return x.AliasFilters
	}
	return nil
}

type LogsFilterAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *StrVal                `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Id            *StrVal                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsFilterAlias) Reset() {
	*x = LogsFilterAlias{}
	mi := &file_alerts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsFilterAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsFilterAlias) ProtoMessage() {}

func (x *LogsFilterAlias) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsFilterAlias.ProtoReflect.Descriptor instead.
func (*LogsFilterAlias) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{12}
}

func (x *LogsFilterAlias) GetAlias() *StrVal {
	if x != nil {
		return x.Alias
	}
	return nil
}

func (x *LogsFilterAlias) GetId() *StrVal {
	if x != nil {
		return x.Id
	}
	return nil
}

type LogsImmediateType struct {
	state                     protoimpl.MessageState                        `protogen:"open.v1"`
	LogsFilter                *LogsFilter                                   `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	NotificationPayloadFilter []*LogsImmediateTypeNotificationPayloadFilter `protobuf:"bytes,2,rep,name=notification_payload_filter,json=notificationPayloadFilter,proto3" json:"notification_payload_filter,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LogsImmediateType) Reset() {
	*x = LogsImmediateType{}
	mi := &file_alerts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsImmediateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsImmediateType) ProtoMessage() {}

func (x *LogsImmediateType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsImmediateType.ProtoReflect.Descriptor instead.
func (*LogsImmediateType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{13}
}

func (x *LogsImmediateType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsImmediateType) GetNotificationPayloadFilter() []*LogsImmediateTypeNotificationPayloadFilter {
	if x != nil {
		return x.NotificationPayloadFilter
	}
	return nil
}

type LogsImmediateTypeNotificationPayloadFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *StrVal                `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsImmediateTypeNotificationPayloadFilter) Reset() {
	*x = LogsImmediateTypeNotificationPayloadFilter{}
	mi := &file_alerts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsImmediateTypeNotificationPayloadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsImmediateTypeNotificationPayloadFilter) ProtoMessage() {}

func (x *LogsImmediateTypeNotificationPayloadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsImmediateTypeNotificationPayloadFilter.ProtoReflect.Descriptor instead.
func (*LogsImmediateTypeNotificationPayloadFilter) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{14}
}

func (x *LogsImmediateTypeNotificationPayloadFilter) GetField() *StrVal {
	if x != nil {
		return x.Field
	}
	return nil
}

type LogsThresholdType struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	LogsFilter                *LogsFilter               `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	Conditions                []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	NotificationPayloadFilter []*StrVal                 `protobuf:"bytes,3,rep,name=notification_payload_filter,json=notificationPayloadFilter,proto3" json:"notification_payload_filter,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LogsThresholdType) Reset() {
	*x = LogsThresholdType{}
	mi := &file_alerts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsThresholdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsThresholdType) ProtoMessage() {}

func (x *LogsThresholdType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsThresholdType.ProtoReflect.Descriptor instead.
func (*LogsThresholdType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{15}
}

func (x *LogsThresholdType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsThresholdType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *LogsThresholdType) GetNotificationPayloadFilter() []*StrVal {
	if x != nil {
		return x.NotificationPayloadFilter
	}
	return nil
}

type LogsThresholdCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     *StrVal                `protobuf:"bytes,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TimeWindow    *TimeWindow            `protobuf:"bytes,2,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	ConditionType *StrVal                `protobuf:"bytes,3,opt,name=condition_type,json=conditionType,proto3" json:"condition_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsThresholdCondition) Reset() {
	*x = LogsThresholdCondition{}
	mi := &file_alerts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsThresholdCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsThresholdCondition) ProtoMessage() {}

func (x *LogsThresholdCondition) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsThresholdCondition.ProtoReflect.Descriptor instead.
func (*LogsThresholdCondition) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{16}
}

func (x *LogsThresholdCondition) GetThreshold() *StrVal {
	if x != nil {
		return x.Threshold
	}
	return nil
}

func (x *LogsThresholdCondition) GetTimeWindow() *TimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

func (x *LogsThresholdCondition) GetConditionType() *StrVal {
	if x != nil {
		return x.ConditionType
	}
	return nil
}

type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *StrVal                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_alerts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{17}
}

func (x *TimeWindow) GetValue() *StrVal {
	if x != nil {
		return x.Value
	}
	return nil
}

type LogsRatioThresholdType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Numerator     *LogsFilter               `protobuf:"bytes,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator   *LogsFilter               `protobuf:"bytes,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRatioThresholdType) Reset() {
	*x = LogsRatioThresholdType{}
	mi := &file_alerts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRatioThresholdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRatioThresholdType) ProtoMessage() {}

func (x *LogsRatioThresholdType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRatioThresholdType.ProtoReflect.Descriptor instead.
func (*LogsRatioThresholdType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{18}
}

func (x *LogsRatioThresholdType) GetNumerator() *LogsFilter {
	if x != nil {
		return x.Numerator
	}
	return nil
}

func (x *LogsRatioThresholdType) GetDenominator() *LogsFilter {
	if x != nil {
		return x.Denominator
	}
	return nil
}

func (x *LogsRatioThresholdType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type LogsTimeRelativeThresholdType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	LogsFilter    *LogsFilter               `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsTimeRelativeThresholdType) Reset() {
	*x = LogsTimeRelativeThresholdType{}
	mi := &file_alerts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsTimeRelativeThresholdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsTimeRelativeThresholdType) ProtoMessage() {}

func (x *LogsTimeRelativeThresholdType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsTimeRelativeThresholdType.ProtoReflect.Descriptor instead.
func (*LogsTimeRelativeThresholdType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{19}
}

func (x *LogsTimeRelativeThresholdType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsTimeRelativeThresholdType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type LogsAnomalyType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	LogsFilter    *LogsFilter               `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsAnomalyType) Reset() {
	*x = LogsAnomalyType{}
	mi := &file_alerts_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsAnomalyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsAnomalyType) ProtoMessage() {}

func (x *LogsAnomalyType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsAnomalyType.ProtoReflect.Descriptor instead.
func (*LogsAnomalyType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{20}
}

func (x *LogsAnomalyType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsAnomalyType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type LogsNewValueType struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LogsFilter     *LogsFilter            `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	KeypathToTrack []*StrVal              `protobuf:"bytes,2,rep,name=keypath_to_track,json=keypathToTrack,proto3" json:"keypath_to_track,omitempty"`
	TimeWindow     *TimeWindow            `protobuf:"bytes,3,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogsNewValueType) Reset() {
	*x = LogsNewValueType{}
	mi := &file_alerts_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsNewValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsNewValueType) ProtoMessage() {}

func (x *LogsNewValueType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsNewValueType.ProtoReflect.Descriptor instead.
func (*LogsNewValueType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{21}
}

func (x *LogsNewValueType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsNewValueType) GetKeypathToTrack() []*StrVal {
	if x != nil {
		return x.KeypathToTrack
	}
	return nil
}

func (x *LogsNewValueType) GetTimeWindow() *TimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

type LogsUniqueCountType struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	LogsFilter         *LogsFilter               `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	UniqueCountKeypath *StrVal                   `protobuf:"bytes,2,opt,name=unique_count_keypath,json=uniqueCountKeypath,proto3" json:"unique_count_keypath,omitempty"`
	Conditions         []*LogsThresholdCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LogsUniqueCountType) Reset() {
	*x = LogsUniqueCountType{}
	mi := &file_alerts_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsUniqueCountType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsUniqueCountType) ProtoMessage() {}

func (x *LogsUniqueCountType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsUniqueCountType.ProtoReflect.Descriptor instead.
func (*LogsUniqueCountType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{22}
}

func (x *LogsUniqueCountType) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *LogsUniqueCountType) GetUniqueCountKeypath() *StrVal {
	if x != nil {
		return x.UniqueCountKeypath
	}
	return nil
}

func (x *LogsUniqueCountType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type TracingImmediateType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TracingFilter *TracingFilter         `protobuf:"bytes,1,opt,name=tracing_filter,json=tracingFilter,proto3" json:"tracing_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracingImmediateType) Reset() {
	*x = TracingImmediateType{}
	mi := &file_alerts_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracingImmediateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingImmediateType) ProtoMessage() {}

func (x *TracingImmediateType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingImmediateType.ProtoReflect.Descriptor instead.
func (*TracingImmediateType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{23}
}

func (x *TracingImmediateType) GetTracingFilter() *TracingFilter {
	if x != nil {
		return x.TracingFilter
	}
	return nil
}

type TracingFilter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LatencyThresholdMs []*TracingFilterField  `protobuf:"bytes,1,rep,name=latency_threshold_ms,json=latencyThresholdMs,proto3" json:"latency_threshold_ms,omitempty"`
	TagFilters         []*TracingFilterField  `protobuf:"bytes,2,rep,name=tag_filters,json=tagFilters,proto3" json:"tag_filters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TracingFilter) Reset() {
	*x = TracingFilter{}
	mi := &file_alerts_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingFilter) ProtoMessage() {}

func (x *TracingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingFilter.ProtoReflect.Descriptor instead.
func (*TracingFilter) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{24}
}

func (x *TracingFilter) GetLatencyThresholdMs() []*TracingFilterField {
	if x != nil {
		return x.LatencyThresholdMs
	}
	return nil
}

func (x *TracingFilter) GetTagFilters() []*TracingFilterField {
	if x != nil {
		return x.TagFilters
	}
	return nil
}

type TracingFilterField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *StrVal                `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Values        []*StrVal              `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracingFilterField) Reset() {
	*x = TracingFilterField{}
	mi := &file_alerts_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracingFilterField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingFilterField) ProtoMessage() {}

func (x *TracingFilterField) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingFilterField.ProtoReflect.Descriptor instead.
func (*TracingFilterField) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{25}
}

func (x *TracingFilterField) GetField() *StrVal {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *TracingFilterField) GetValues() []*StrVal {
	if x != nil {
		return x.Values
	}
	return nil
}

type TracingThresholdType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TracingFilter *TracingFilter            `protobuf:"bytes,1,opt,name=tracing_filter,json=tracingFilter,proto3" json:"tracing_filter,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracingThresholdType) Reset() {
	*x = TracingThresholdType{}
	mi := &file_alerts_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracingThresholdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingThresholdType) ProtoMessage() {}

func (x *TracingThresholdType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingThresholdType.ProtoReflect.Descriptor instead.
func (*TracingThresholdType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{26}
}

func (x *TracingThresholdType) GetTracingFilter() *TracingFilter {
	if x != nil {
		return x.TracingFilter
	}
	return nil
}

func (x *TracingThresholdType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type MetricThresholdType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MetricFilter  *StrVal                   `protobuf:"bytes,1,opt,name=metric_filter,json=metricFilter,proto3" json:"metric_filter,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricThresholdType) Reset() {
	*x = MetricThresholdType{}
	mi := &file_alerts_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricThresholdType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricThresholdType) ProtoMessage() {}

func (x *MetricThresholdType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricThresholdType.ProtoReflect.Descriptor instead.
func (*MetricThresholdType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{27}
}

func (x *MetricThresholdType) GetMetricFilter() *StrVal {
	if x != nil {
		return x.MetricFilter
	}
	return nil
}

func (x *MetricThresholdType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type MetricAnomalyType struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MetricFilter  *StrVal                   `protobuf:"bytes,1,opt,name=metric_filter,json=metricFilter,proto3" json:"metric_filter,omitempty"`
	Conditions    []*LogsThresholdCondition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricAnomalyType) Reset() {
	*x = MetricAnomalyType{}
	mi := &file_alerts_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAnomalyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAnomalyType) ProtoMessage() {}

func (x *MetricAnomalyType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAnomalyType.ProtoReflect.Descriptor instead.
func (*MetricAnomalyType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{28}
}

func (x *MetricAnomalyType) GetMetricFilter() *StrVal {
	if x != nil {
		return x.MetricFilter
	}
	return nil
}

func (x *MetricAnomalyType) GetConditions() []*LogsThresholdCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type FlowType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []*FlowStage           `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowType) Reset() {
	*x = FlowType{}
	mi := &file_alerts_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowType) ProtoMessage() {}

func (x *FlowType) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowType.ProtoReflect.Descriptor instead.
func (*FlowType) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{29}
}

func (x *FlowType) GetStages() []*FlowStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type FlowStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*FlowStageGroup      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Timeframe     *TimeWindow            `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowStage) Reset() {
	*x = FlowStage{}
	mi := &file_alerts_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowStage) ProtoMessage() {}

func (x *FlowStage) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowStage.ProtoReflect.Descriptor instead.
func (*FlowStage) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{30}
}

func (x *FlowStage) GetGroups() []*FlowStageGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *FlowStage) GetTimeframe() *TimeWindow {
	if x != nil {
		return x.Timeframe
	}
	return nil
}

type FlowStageGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogsFilter    *LogsFilter            `protobuf:"bytes,1,opt,name=logs_filter,json=logsFilter,proto3" json:"logs_filter,omitempty"`
	AlertDefId    *StrVal                `protobuf:"bytes,2,opt,name=alert_def_id,json=alertDefId,proto3" json:"alert_def_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowStageGroup) Reset() {
	*x = FlowStageGroup{}
	mi := &file_alerts_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowStageGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowStageGroup) ProtoMessage() {}

func (x *FlowStageGroup) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowStageGroup.ProtoReflect.Descriptor instead.
func (*FlowStageGroup) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{31}
}

func (x *FlowStageGroup) GetLogsFilter() *LogsFilter {
	if x != nil {
		return x.LogsFilter
	}
	return nil
}

func (x *FlowStageGroup) GetAlertDefId() *StrVal {
	if x != nil {
		return x.AlertDefId
	}
	return nil
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12\x1bcom.coralogixapis.alerts.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\x06StrVal\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x16\n" +
	"\x14ListAlertDefsRequest\"]\n" +
	"\x15ListAlertDefsResponse\x12D\n" +
	"\n" +
	"alert_defs\x18\x01 \x03(\v2%.com.coralogixapis.alerts.v3.AlertDefR\talertDefs\"I\n" +
	"\x12GetAlertDefRequest\x123\n" +
	"\x02id\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x02id\"Y\n" +
	"\x13GetAlertDefResponse\x12B\n" +
	"\talert_def\x18\x01 \x01(\v2%.com.coralogixapis.alerts.v3.AlertDefR\balertDef\"\xbb\x03\n" +
	"\bAlertDef\x12a\n" +
	"\x14alert_def_properties\x18\x01 \x01(\v2/.com.coralogixapis.alerts.v3.AlertDefPropertiesR\x12alertDefProperties\x123\n" +
	"\x02id\x18\x02 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x02id\x12M\n" +
	"\x10alert_version_id\x18\x14 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x0ealertVersionId\x12=\n" +
	"\fcreated_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12=\n" +
	"\fupdated_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedTime\x12J\n" +
	"\x13last_triggered_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastTriggeredTime\"\xd2\x10\n" +
	"\x12AlertDefProperties\x127\n" +
	"\x04name\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x04name\x12E\n" +
	"\vdescription\x18\x02 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\vdescription\x124\n" +
	"\aenabled\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\aenabled\x12I\n" +
	"\bpriority\x18\x04 \x01(\x0e2-.com.coralogixapis.alerts.v3.AlertDefPriorityR\bpriority\x12L\n" +
	"\tactive_on\x18\x05 \x01(\v2-.com.coralogixapis.alerts.v3.ActivityScheduleH\x00R\bactiveOn\x12=\n" +
	"\x04type\x18\x06 \x01(\x0e2).com.coralogixapis.alerts.v3.AlertDefTypeR\x04type\x12W\n" +
	"\x0elogs_immediate\x18e \x01(\v2..com.coralogixapis.alerts.v3.LogsImmediateTypeH\x01R\rlogsImmediate\x12`\n" +
	"\x11tracing_immediate\x18f \x01(\v21.com.coralogixapis.alerts.v3.TracingImmediateTypeH\x01R\x10tracingImmediate\x12W\n" +
	"\x0elogs_threshold\x18g \x01(\v2..com.coralogixapis.alerts.v3.LogsThresholdTypeH\x01R\rlogsThreshold\x12g\n" +
	"\x14logs_ratio_threshold\x18h \x01(\v23.com.coralogixapis.alerts.v3.LogsRatioThresholdTypeH\x01R\x12logsRatioThreshold\x12}\n" +
	"\x1clogs_time_relative_threshold\x18i \x01(\v2:.com.coralogixapis.alerts.v3.LogsTimeRelativeThresholdTypeH\x01R\x19logsTimeRelativeThreshold\x12]\n" +
	"\x10metric_threshold\x18j \x01(\v20.com.coralogixapis.alerts.v3.MetricThresholdTypeH\x01R\x0fmetricThreshold\x12`\n" +
	"\x11tracing_threshold\x18k \x01(\v21.com.coralogixapis.alerts.v3.TracingThresholdTypeH\x01R\x10tracingThreshold\x12;\n" +
	"\x04flow\x18l \x01(\v2%.com.coralogixapis.alerts.v3.FlowTypeH\x01R\x04flow\x12Q\n" +
	"\flogs_anomaly\x18m \x01(\v2,.com.coralogixapis.alerts.v3.LogsAnomalyTypeH\x01R\vlogsAnomaly\x12W\n" +
	"\x0emetric_anomaly\x18n \x01(\v2..com.coralogixapis.alerts.v3.MetricAnomalyTypeH\x01R\rmetricAnomaly\x12U\n" +
	"\x0elogs_new_value\x18o \x01(\v2-.com.coralogixapis.alerts.v3.LogsNewValueTypeH\x01R\flogsNewValue\x12^\n" +
	"\x11logs_unique_count\x18p \x01(\v20.com.coralogixapis.alerts.v3.LogsUniqueCountTypeH\x01R\x0flogsUniqueCount\x12G\n" +
	"\rgroup_by_keys\x18\a \x03(\v2#.com.coralogixapis.alerts.v3.StrValR\vgroupByKeys\x12d\n" +
	"\x12incidents_settings\x18\b \x01(\v25.com.coralogixapis.alerts.v3.AlertDefIncidentSettingsR\x11incidentsSettings\x12e\n" +
	"\x12notification_group\x18\t \x01(\v26.com.coralogixapis.alerts.v3.AlertDefNotificationGroupR\x11notificationGroup\x12f\n" +
	"\rentity_labels\x18\n" +
	" \x03(\v2A.com.coralogixapis.alerts.v3.AlertDefProperties.EntityLabelsEntryR\fentityLabels\x12=\n" +
	"\fphantom_mode\x18\v \x01(\v2\x1a.google.protobuf.BoolValueR\vphantomMode\x124\n" +
	"\adeleted\x18\f \x01(\v2\x1a.google.protobuf.BoolValueR\adeleted\x1a?\n" +
	"\x11EntityLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\n" +
	"\n" +
	"\bscheduleB\x11\n" +
	"\x0ftype_definition\"\xe4\x01\n" +
	"\x10ActivitySchedule\x12F\n" +
	"\vday_of_week\x18\x01 \x03(\x0e2&.com.coralogixapis.alerts.v3.DayOfWeekR\tdayOfWeek\x12E\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2&.com.coralogixapis.alerts.v3.TimeOfDayR\tstartTime\x12A\n" +
	"\bend_time\x18\x03 \x01(\v2&.com.coralogixapis.alerts.v3.TimeOfDayR\aendTime\";\n" +
	"\tTimeOfDay\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"T\n" +
	"\x18AlertDefIncidentSettings\x128\n" +
	"\tnotify_on\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\bnotifyOn\"h\n" +
	"\x19AlertDefNotificationGroup\x12K\n" +
	"\x0fgroup_by_fields\x18\x01 \x03(\v2#.com.coralogixapis.alerts.v3.StrValR\rgroupByFields\"\xa9\x01\n" +
	"\n" +
	"LogsFilter\x12H\n" +
	"\rlucene_filter\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\fluceneFilter\x12Q\n" +
	"\ralias_filters\x18\x02 \x03(\v2,.com.coralogixapis.alerts.v3.LogsFilterAliasR\faliasFilters\"\x81\x01\n" +
	"\x0fLogsFilterAlias\x129\n" +
	"\x05alias\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x05alias\x123\n" +
	"\x02id\x18\x02 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x02id\"\xe7\x01\n" +
	"\x11LogsImmediateType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12\x87\x01\n" +
	"\x1bnotification_payload_filter\x18\x02 \x03(\v2G.com.coralogixapis.alerts.v3.LogsImmediateTypeNotificationPayloadFilterR\x19notificationPayloadFilter\"g\n" +
	"*LogsImmediateTypeNotificationPayloadFilter\x129\n" +
	"\x05field\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x05field\"\x97\x02\n" +
	"\x11LogsThresholdType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\x12c\n" +
	"\x1bnotification_payload_filter\x18\x03 \x03(\v2#.com.coralogixapis.alerts.v3.StrValR\x19notificationPayloadFilter\"\xf1\x01\n" +
	"\x16LogsThresholdCondition\x12A\n" +
	"\tthreshold\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\tthreshold\x12H\n" +
	"\vtime_window\x18\x02 \x01(\v2'.com.coralogixapis.alerts.v3.TimeWindowR\n" +
	"timeWindow\x12J\n" +
	"\x0econdition_type\x18\x03 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\rconditionType\"G\n" +
	"\n" +
	"TimeWindow\x129\n" +
	"\x05value\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x05value\"\xff\x01\n" +
	"\x16LogsRatioThresholdType\x12E\n" +
	"\tnumerator\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\tnumerator\x12I\n" +
	"\vdenominator\x18\x02 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\vdenominator\x12S\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"\xbe\x01\n" +
	"\x1dLogsTimeRelativeThresholdType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"\xb0\x01\n" +
	"\x0fLogsAnomalyType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"\xf5\x01\n" +
	"\x10LogsNewValueType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12M\n" +
	"\x10keypath_to_track\x18\x02 \x03(\v2#.com.coralogixapis.alerts.v3.StrValR\x0ekeypathToTrack\x12H\n" +
	"\vtime_window\x18\x03 \x01(\v2'.com.coralogixapis.alerts.v3.TimeWindowR\n" +
	"timeWindow\"\x8b\x02\n" +
	"\x13LogsUniqueCountType\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12U\n" +
	"\x14unique_count_keypath\x18\x02 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x12uniqueCountKeypath\x12S\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"i\n" +
	"\x14TracingImmediateType\x12Q\n" +
	"\x0etracing_filter\x18\x01 \x01(\v2*.com.coralogixapis.alerts.v3.TracingFilterR\rtracingFilter\"\xc4\x01\n" +
	"\rTracingFilter\x12a\n" +
	"\x14latency_threshold_ms\x18\x01 \x03(\v2/.com.coralogixapis.alerts.v3.TracingFilterFieldR\x12latencyThresholdMs\x12P\n" +
	"\vtag_filters\x18\x02 \x03(\v2/.com.coralogixapis.alerts.v3.TracingFilterFieldR\n" +
	"tagFilters\"\x8c\x01\n" +
	"\x12TracingFilterField\x129\n" +
	"\x05field\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\x05field\x12;\n" +
	"\x06values\x18\x02 \x03(\v2#.com.coralogixapis.alerts.v3.StrValR\x06values\"\xbe\x01\n" +
	"\x14TracingThresholdType\x12Q\n" +
	"\x0etracing_filter\x18\x01 \x01(\v2*.com.coralogixapis.alerts.v3.TracingFilterR\rtracingFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"\xb4\x01\n" +
	"\x13MetricThresholdType\x12H\n" +
	"\rmetric_filter\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\fmetricFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"\xb2\x01\n" +
	"\x11MetricAnomalyType\x12H\n" +
	"\rmetric_filter\x18\x01 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\fmetricFilter\x12S\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v23.com.coralogixapis.alerts.v3.LogsThresholdConditionR\n" +
	"conditions\"J\n" +
	"\bFlowType\x12>\n" +
	"\x06stages\x18\x01 \x03(\v2&.com.coralogixapis.alerts.v3.FlowStageR\x06stages\"\x97\x01\n" +
	"\tFlowStage\x12C\n" +
	"\x06groups\x18\x01 \x03(\v2+.com.coralogixapis.alerts.v3.FlowStageGroupR\x06groups\x12E\n" +
	"\ttimeframe\x18\x02 \x01(\v2'.com.coralogixapis.alerts.v3.TimeWindowR\ttimeframe\"\xa1\x01\n" +
	"\x0eFlowStageGroup\x12H\n" +
	"\vlogs_filter\x18\x01 \x01(\v2'.com.coralogixapis.alerts.v3.LogsFilterR\n" +
	"logsFilter\x12E\n" +
	"\falert_def_id\x18\x02 \x01(\v2#.com.coralogixapis.alerts.v3.StrValR\n" +
	"alertDefId*\xc3\x01\n" +
	"\x10AlertDefPriority\x12(\n" +
	"$ALERT_DEF_PRIORITY_P5_OR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ALERT_DEF_PRIORITY_P1\x10\x01\x12\x19\n" +
	"\x15ALERT_DEF_PRIORITY_P2\x10\x02\x12\x19\n" +
	"\x15ALERT_DEF_PRIORITY_P3\x10\x03\x12\x19\n" +
	"\x15ALERT_DEF_PRIORITY_P4\x10\x04\x12\x19\n" +
	"\x15ALERT_DEF_PRIORITY_P5\x10\x05*\xd4\x03\n" +
	"\fAlertDefType\x120\n" +
	",ALERT_DEF_TYPE_LOGS_IMMEDIATE_OR_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dALERT_DEF_TYPE_LOGS_THRESHOLD\x10\x01\x12'\n" +
	"#ALERT_DEF_TYPE_LOGS_RATIO_THRESHOLD\x10\x02\x12/\n" +
	"+ALERT_DEF_TYPE_LOGS_TIME_RELATIVE_THRESHOLD\x10\x03\x12\x1f\n" +
	"\x1bALERT_DEF_TYPE_LOGS_ANOMALY\x10\x04\x12!\n" +
	"\x1dALERT_DEF_TYPE_LOGS_NEW_VALUE\x10\x05\x12$\n" +
	" ALERT_DEF_TYPE_LOGS_UNIQUE_COUNT\x10\x06\x12#\n" +
	"\x1fALERT_DEF_TYPE_METRIC_THRESHOLD\x10\a\x12!\n" +
	"\x1dALERT_DEF_TYPE_METRIC_ANOMALY\x10\b\x12$\n" +
	" ALERT_DEF_TYPE_TRACING_IMMEDIATE\x10\t\x12$\n" +
	" ALERT_DEF_TYPE_TRACING_THRESHOLD\x10\n" +
	"\x12\x17\n" +
	"\x13ALERT_DEF_TYPE_FLOW\x10\v*\xca\x01\n" +
	"\tDayOfWeek\x12%\n" +
	"!DAY_OF_WEEK_MONDAY_OR_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DAY_OF_WEEK_TUESDAY\x10\x01\x12\x19\n" +
	"\x15DAY_OF_WEEK_WEDNESDAY\x10\x02\x12\x18\n" +
	"\x14DAY_OF_WEEK_THURSDAY\x10\x03\x12\x16\n" +
	"\x12DAY_OF_WEEK_FRIDAY\x10\x04\x12\x18\n" +
	"\x14DAY_OF_WEEK_SATURDAY\x10\x05\x12\x16\n" +
	"\x12DAY_OF_WEEK_SUNDAY\x10\x062\xfc\x01\n" +
	"\x10AlertDefsService\x12v\n" +
	"\rListAlertDefs\x121.com.coralogixapis.alerts.v3.ListAlertDefsRequest\x1a2.com.coralogixapis.alerts.v3.ListAlertDefsResponse\x12p\n" +
	"\vGetAlertDef\x12/.com.coralogixapis.alerts.v3.GetAlertDefRequest\x1a0.com.coralogixapis.alerts.v3.GetAlertDefResponseB<Z:coralogix-alert-analyzer/internal/coralogix/proto;alertspbb\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_alerts_proto_goTypes = []any{
	(AlertDefPriority)(0),                              // 0: com.coralogixapis.alerts.v3.AlertDefPriority
	(AlertDefType)(0),                                  // 1: com.coralogixapis.alerts.v3.AlertDefType
	(DayOfWeek)(0),                                     // 2: com.coralogixapis.alerts.v3.DayOfWeek
	(*StrVal)(nil),                                     // 3: com.coralogixapis.alerts.v3.StrVal
	(*ListAlertDefsRequest)(nil),                       // 4: com.coralogixapis.alerts.v3.ListAlertDefsRequest
	(*ListAlertDefsResponse)(nil),                      // 5: com.coralogixapis.alerts.v3.ListAlertDefsResponse
	(*GetAlertDefRequest)(nil),                         // 6: com.coralogixapis.alerts.v3.GetAlertDefRequest
	(*GetAlertDefResponse)(nil),                        // 7: com.coralogixapis.alerts.v3.GetAlertDefResponse
	(*AlertDef)(nil),                                   // 8: com.coralogixapis.alerts.v3.AlertDef
	(*AlertDefProperties)(nil),                         // 9: com.coralogixapis.alerts.v3.AlertDefProperties
	(*ActivitySchedule)(nil),                           // 10: com.coralogixapis.alerts.v3.ActivitySchedule
	(*TimeOfDay)(nil),                                  // 11: com.coralogixapis.alerts.v3.TimeOfDay
	(*AlertDefIncidentSettings)(nil),                   // 12: com.coralogixapis.alerts.v3.AlertDefIncidentSettings
	(*AlertDefNotificationGroup)(nil),                  // 13: com.coralogixapis.alerts.v3.AlertDefNotificationGroup
	(*LogsFilter)(nil),                                 // 14: com.coralogixapis.alerts.v3.LogsFilter
	(*LogsFilterAlias)(nil),                            // 15: com.coralogixapis.alerts.v3.LogsFilterAlias
	(*LogsImmediateType)(nil),                          // 16: com.coralogixapis.alerts.v3.LogsImmediateType
	(*LogsImmediateTypeNotificationPayloadFilter)(nil), // 17: com.coralogixapis.alerts.v3.LogsImmediateTypeNotificationPayloadFilter
	(*LogsThresholdType)(nil),                          // 18: com.coralogixapis.alerts.v3.LogsThresholdType
	(*LogsThresholdCondition)(nil),                     // 19: com.coralogixapis.alerts.v3.LogsThresholdCondition
	(*TimeWindow)(nil),                                 // 20: com.coralogixapis.alerts.v3.TimeWindow
	(*LogsRatioThresholdType)(nil),                     // 21: com.coralogixapis.alerts.v3.LogsRatioThresholdType
	(*LogsTimeRelativeThresholdType)(nil),              // 22: com.coralogixapis.alerts.v3.LogsTimeRelativeThresholdType
	(*LogsAnomalyType)(nil),                            // 23: com.coralogixapis.alerts.v3.LogsAnomalyType
	(*LogsNewValueType)(nil),                           // 24: com.coralogixapis.alerts.v3.LogsNewValueType
	(*LogsUniqueCountType)(nil),                        // 25: com.coralogixapis.alerts.v3.LogsUniqueCountType
	(*TracingImmediateType)(nil),                       // 26: com.coralogixapis.alerts.v3.TracingImmediateType
	(*TracingFilter)(nil),                              // 27: com.coralogixapis.alerts.v3.TracingFilter
	(*TracingFilterField)(nil),                         // 28: com.coralogixapis.alerts.v3.TracingFilterField
	(*TracingThresholdType)(nil),                       // 29: com.coralogixapis.alerts.v3.TracingThresholdType
	(*MetricThresholdType)(nil),                        // 30: com.coralogixapis.alerts.v3.MetricThresholdType
	(*MetricAnomalyType)(nil),                          // 31: com.coralogixapis.alerts.v3.MetricAnomalyType
	(*FlowType)(nil),                                   // 32: com.coralogixapis.alerts.v3.FlowType
	(*FlowStage)(nil),                                  // 33: com.coralogixapis.alerts.v3.FlowStage
	(*FlowStageGroup)(nil),                             // 34: com.coralogixapis.alerts.v3.FlowStageGroup
	nil,                                                // 35: com.coralogixapis.alerts.v3.AlertDefProperties.EntityLabelsEntry
	(*timestamppb.Timestamp)(nil),                      // 36: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),                       // 37: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),                      // 38: google.protobuf.Int32Value
}
var file_alerts_proto_depIdxs = []int32{
	8,  // 0: com.coralogixapis.alerts.v3.ListAlertDefsResponse.alert_defs:type_name -> com.coralogixapis.alerts.v3.AlertDef
	3,  // 1: com.coralogixapis.alerts.v3.GetAlertDefRequest.id:type_name -> com.coralogixapis.alerts.v3.StrVal
	8,  // 2: com.coralogixapis.alerts.v3.GetAlertDefResponse.alert_def:type_name -> com.coralogixapis.alerts.v3.AlertDef
	9,  // 3: com.coralogixapis.alerts.v3.AlertDef.alert_def_properties:type_name -> com.coralogixapis.alerts.v3.AlertDefProperties
	3,  // 4: com.coralogixapis.alerts.v3.AlertDef.id:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 5: com.coralogixapis.alerts.v3.AlertDef.alert_version_id:type_name -> com.coralogixapis.alerts.v3.StrVal
	36, // 6: com.coralogixapis.alerts.v3.AlertDef.created_time:type_name -> google.protobuf.Timestamp
	36, // 7: com.coralogixapis.alerts.v3.AlertDef.updated_time:type_name -> google.protobuf.Timestamp
	36, // 8: com.coralogixapis.alerts.v3.AlertDef.last_triggered_time:type_name -> google.protobuf.Timestamp
	3,  // 9: com.coralogixapis.alerts.v3.AlertDefProperties.name:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 10: com.coralogixapis.alerts.v3.AlertDefProperties.description:type_name -> com.coralogixapis.alerts.v3.StrVal
	37, // 11: com.coralogixapis.alerts.v3.AlertDefProperties.enabled:type_name -> google.protobuf.BoolValue
	0,  // 12: com.coralogixapis.alerts.v3.AlertDefProperties.priority:type_name -> com.coralogixapis.alerts.v3.AlertDefPriority
	10, // 13: com.coralogixapis.alerts.v3.AlertDefProperties.active_on:type_name -> com.coralogixapis.alerts.v3.ActivitySchedule
	1,  // 14: com.coralogixapis.alerts.v3.AlertDefProperties.type:type_name -> com.coralogixapis.alerts.v3.AlertDefType
	16, // 15: com.coralogixapis.alerts.v3.AlertDefProperties.logs_immediate:type_name -> com.coralogixapis.alerts.v3.LogsImmediateType
	26, // 16: com.coralogixapis.alerts.v3.AlertDefProperties.tracing_immediate:type_name -> com.coralogixapis.alerts.v3.TracingImmediateType
	18, // 17: com.coralogixapis.alerts.v3.AlertDefProperties.logs_threshold:type_name -> com.coralogixapis.alerts.v3.LogsThresholdType
	21, // 18: com.coralogixapis.alerts.v3.AlertDefProperties.logs_ratio_threshold:type_name -> com.coralogixapis.alerts.v3.LogsRatioThresholdType
	22, // 19: com.coralogixapis.alerts.v3.AlertDefProperties.logs_time_relative_threshold:type_name -> com.coralogixapis.alerts.v3.LogsTimeRelativeThresholdType
	30, // 20: com.coralogixapis.alerts.v3.AlertDefProperties.metric_threshold:type_name -> com.coralogixapis.alerts.v3.MetricThresholdType
	29, // 21: com.coralogixapis.alerts.v3.AlertDefProperties.tracing_threshold:type_name -> com.coralogixapis.alerts.v3.TracingThresholdType
	32, // 22: com.coralogixapis.alerts.v3.AlertDefProperties.flow:type_name -> com.coralogixapis.alerts.v3.FlowType
	23, // 23: com.coralogixapis.alerts.v3.AlertDefProperties.logs_anomaly:type_name -> com.coralogixapis.alerts.v3.LogsAnomalyType
	31, // 24: com.coralogixapis.alerts.v3.AlertDefProperties.metric_anomaly:type_name -> com.coralogixapis.alerts.v3.MetricAnomalyType
	24, // 25: com.coralogixapis.alerts.v3.AlertDefProperties.logs_new_value:type_name -> com.coralogixapis.alerts.v3.LogsNewValueType
	25, // 26: com.coralogixapis.alerts.v3.AlertDefProperties.logs_unique_count:type_name -> com.coralogixapis.alerts.v3.LogsUniqueCountType
	3,  // 27: com.coralogixapis.alerts.v3.AlertDefProperties.group_by_keys:type_name -> com.coralogixapis.alerts.v3.StrVal
	12, // 28: com.coralogixapis.alerts.v3.AlertDefProperties.incidents_settings:type_name -> com.coralogixapis.alerts.v3.AlertDefIncidentSettings
	13, // 29: com.coralogixapis.alerts.v3.AlertDefProperties.notification_group:type_name -> com.coralogixapis.alerts.v3.AlertDefNotificationGroup
	35, // 30: com.coralogixapis.alerts.v3.AlertDefProperties.entity_labels:type_name -> com.coralogixapis.alerts.v3.AlertDefProperties.EntityLabelsEntry
	37, // 31: com.coralogixapis.alerts.v3.AlertDefProperties.phantom_mode:type_name -> google.protobuf.BoolValue
	37, // 32: com.coralogixapis.alerts.v3.AlertDefProperties.deleted:type_name -> google.protobuf.BoolValue
	2,  // 33: com.coralogixapis.alerts.v3.ActivitySchedule.day_of_week:type_name -> com.coralogixapis.alerts.v3.DayOfWeek
	11, // 34: com.coralogixapis.alerts.v3.ActivitySchedule.start_time:type_name -> com.coralogixapis.alerts.v3.TimeOfDay
	11, // 35: com.coralogixapis.alerts.v3.ActivitySchedule.end_time:type_name -> com.coralogixapis.alerts.v3.TimeOfDay
	38, // 36: com.coralogixapis.alerts.v3.AlertDefIncidentSettings.notify_on:type_name -> google.protobuf.Int32Value
	3,  // 37: com.coralogixapis.alerts.v3.AlertDefNotificationGroup.group_by_fields:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 38: com.coralogixapis.alerts.v3.LogsFilter.lucene_filter:type_name -> com.coralogixapis.alerts.v3.StrVal
	15, // 39: com.coralogixapis.alerts.v3.LogsFilter.alias_filters:type_name -> com.coralogixapis.alerts.v3.LogsFilterAlias
	3,  // 40: com.coralogixapis.alerts.v3.LogsFilterAlias.alias:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 41: com.coralogixapis.alerts.v3.LogsFilterAlias.id:type_name -> com.coralogixapis.alerts.v3.StrVal
	14, // 42: com.coralogixapis.alerts.v3.LogsImmediateType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	17, // 43: com.coralogixapis.alerts.v3.LogsImmediateType.notification_payload_filter:type_name -> com.coralogixapis.alerts.v3.LogsImmediateTypeNotificationPayloadFilter
	3,  // 44: com.coralogixapis.alerts.v3.LogsImmediateTypeNotificationPayloadFilter.field:type_name -> com.coralogixapis.alerts.v3.StrVal
	14, // 45: com.coralogixapis.alerts.v3.LogsThresholdType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	19, // 46: com.coralogixapis.alerts.v3.LogsThresholdType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	3,  // 47: com.coralogixapis.alerts.v3.LogsThresholdType.notification_payload_filter:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 48: com.coralogixapis.alerts.v3.LogsThresholdCondition.threshold:type_name -> com.coralogixapis.alerts.v3.StrVal
	20, // 49: com.coralogixapis.alerts.v3.LogsThresholdCondition.time_window:type_name -> com.coralogixapis.alerts.v3.TimeWindow
	3,  // 50: com.coralogixapis.alerts.v3.LogsThresholdCondition.condition_type:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 51: com.coralogixapis.alerts.v3.TimeWindow.value:type_name -> com.coralogixapis.alerts.v3.StrVal
	14, // 52: com.coralogixapis.alerts.v3.LogsRatioThresholdType.numerator:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	14, // 53: com.coralogixapis.alerts.v3.LogsRatioThresholdType.denominator:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	19, // 54: com.coralogixapis.alerts.v3.LogsRatioThresholdType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	14, // 55: com.coralogixapis.alerts.v3.LogsTimeRelativeThresholdType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	19, // 56: com.coralogixapis.alerts.v3.LogsTimeRelativeThresholdType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	14, // 57: com.coralogixapis.alerts.v3.LogsAnomalyType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	19, // 58: com.coralogixapis.alerts.v3.LogsAnomalyType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	14, // 59: com.coralogixapis.alerts.v3.LogsNewValueType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	3,  // 60: com.coralogixapis.alerts.v3.LogsNewValueType.keypath_to_track:type_name -> com.coralogixapis.alerts.v3.StrVal
	20, // 61: com.coralogixapis.alerts.v3.LogsNewValueType.time_window:type_name -> com.coralogixapis.alerts.v3.TimeWindow
	14, // 62: com.coralogixapis.alerts.v3.LogsUniqueCountType.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	3,  // 63: com.coralogixapis.alerts.v3.LogsUniqueCountType.unique_count_keypath:type_name -> com.coralogixapis.alerts.v3.StrVal
	19, // 64: com.coralogixapis.alerts.v3.LogsUniqueCountType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	27, // 65: com.coralogixapis.alerts.v3.TracingImmediateType.tracing_filter:type_name -> com.coralogixapis.alerts.v3.TracingFilter
	28, // 66: com.coralogixapis.alerts.v3.TracingFilter.latency_threshold_ms:type_name -> com.coralogixapis.alerts.v3.TracingFilterField
	28, // 67: com.coralogixapis.alerts.v3.TracingFilter.tag_filters:type_name -> com.coralogixapis.alerts.v3.TracingFilterField
	3,  // 68: com.coralogixapis.alerts.v3.TracingFilterField.field:type_name -> com.coralogixapis.alerts.v3.StrVal
	3,  // 69: com.coralogixapis.alerts.v3.TracingFilterField.values:type_name -> com.coralogixapis.alerts.v3.StrVal
	27, // 70: com.coralogixapis.alerts.v3.TracingThresholdType.tracing_filter:type_name -> com.coralogixapis.alerts.v3.TracingFilter
	19, // 71: com.coralogixapis.alerts.v3.TracingThresholdType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	3,  // 72: com.coralogixapis.alerts.v3.MetricThresholdType.metric_filter:type_name -> com.coralogixapis.alerts.v3.StrVal
	19, // 73: com.coralogixapis.alerts.v3.MetricThresholdType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	3,  // 74: com.coralogixapis.alerts.v3.MetricAnomalyType.metric_filter:type_name -> com.coralogixapis.alerts.v3.StrVal
	19, // 75: com.coralogixapis.alerts.v3.MetricAnomalyType.conditions:type_name -> com.coralogixapis.alerts.v3.LogsThresholdCondition
	33, // 76: com.coralogixapis.alerts.v3.FlowType.stages:type_name -> com.coralogixapis.alerts.v3.FlowStage
	34, // 77: com.coralogixapis.alerts.v3.FlowStage.groups:type_name -> com.coralogixapis.alerts.v3.FlowStageGroup
	20, // 78: com.coralogixapis.alerts.v3.FlowStage.timeframe:type_name -> com.coralogixapis.alerts.v3.TimeWindow
	14, // 79: com.coralogixapis.alerts.v3.FlowStageGroup.logs_filter:type_name -> com.coralogixapis.alerts.v3.LogsFilter
	3,  // 80: com.coralogixapis.alerts.v3.FlowStageGroup.alert_def_id:type_name -> com.coralogixapis.alerts.v3.StrVal
	4,  // 81: com.coralogixapis.alerts.v3.AlertDefsService.ListAlertDefs:input_type -> com.coralogixapis.alerts.v3.ListAlertDefsRequest
	6,  // 82: com.coralogixapis.alerts.v3.AlertDefsService.GetAlertDef:input_type -> com.coralogixapis.alerts.v3.GetAlertDefRequest
	5,  // 83: com.coralogixapis.alerts.v3.AlertDefsService.ListAlertDefs:output_type -> com.coralogixapis.alerts.v3.ListAlertDefsResponse
	7,  // 84: com.coralogixapis.alerts.v3.AlertDefsService.GetAlertDef:output_type -> com.coralogixapis.alerts.v3.GetAlertDefResponse
	83, // [83:85] is the sub-list for method output_type
	81, // [81:83] is the sub-list for method input_type
	81, // [81:81] is the sub-list for extension type_name
	81, // [81:81] is the sub-list for extension extendee
	0,  // [0:81] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	file_alerts_proto_msgTypes[6].OneofWrappers = []any{
		(*AlertDefProperties_ActiveOn)(nil),
		(*AlertDefProperties_LogsImmediate)(nil),
		(*AlertDefProperties_TracingImmediate)(nil),
		(*AlertDefProperties_LogsThreshold)(nil),
		(*AlertDefProperties_LogsRatioThreshold)(nil),
		(*AlertDefProperties_LogsTimeRelativeThreshold)(nil),
		(*AlertDefProperties_MetricThreshold)(nil),
		(*AlertDefProperties_TracingThreshold)(nil),
		(*AlertDefProperties_Flow)(nil),
		(*AlertDefProperties_LogsAnomaly)(nil),
		(*AlertDefProperties_MetricAnomaly)(nil),
		(*AlertDefProperties_LogsNewValue)(nil),
		(*AlertDefProperties_LogsUniqueCount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		EnumInfos:         file_alerts_proto_enumTypes,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
