// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: alerts.proto

package alertspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertDefsService_ListAlertDefs_FullMethodName = "/com.coralogixapis.alerts.v3.AlertDefsService/ListAlertDefs"
	AlertDefsService_GetAlertDef_FullMethodName   = "/com.coralogixapis.alerts.v3.AlertDefsService/GetAlertDef"
)

// AlertDefsServiceClient is the client API for AlertDefsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertDefsServiceClient interface {
	ListAlertDefs(ctx context.Context, in *ListAlertDefsRequest, opts ...grpc.CallOption) (*ListAlertDefsResponse, error)
	GetAlertDef(ctx context.Context, in *GetAlertDefRequest, opts ...grpc.CallOption) (*GetAlertDefResponse, error)
}

type alertDefsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertDefsServiceClient(cc grpc.ClientConnInterface) AlertDefsServiceClient {
	return &alertDefsServiceClient{cc}
}

func (c *alertDefsServiceClient) ListAlertDefs(ctx context.Context, in *ListAlertDefsRequest, opts ...grpc.CallOption) (*ListAlertDefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertDefsResponse)
	err := c.cc.Invoke(ctx, AlertDefsService_ListAlertDefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertDefsServiceClient) GetAlertDef(ctx context.Context, in *GetAlertDefRequest, opts ...grpc.CallOption) (*GetAlertDefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertDefResponse)
	err := c.cc.Invoke(ctx, AlertDefsService_GetAlertDef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertDefsServiceServer is the server API for AlertDefsService service.
// All implementations must embed UnimplementedAlertDefsServiceServer
// for forward compatibility.
type AlertDefsServiceServer interface {
	ListAlertDefs(context.Context, *ListAlertDefsRequest) (*ListAlertDefsResponse, error)
	GetAlertDef(context.Context, *GetAlertDefRequest) (*GetAlertDefResponse, error)
	mustEmbedUnimplementedAlertDefsServiceServer()
}

// UnimplementedAlertDefsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertDefsServiceServer struct{}

func (UnimplementedAlertDefsServiceServer) ListAlertDefs(context.Context, *ListAlertDefsRequest) (*ListAlertDefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlertDefs not implemented")
}
func (UnimplementedAlertDefsServiceServer) GetAlertDef(context.Context, *GetAlertDefRequest) (*GetAlertDefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertDef not implemented")
}
func (UnimplementedAlertDefsServiceServer) mustEmbedUnimplementedAlertDefsServiceServer() {}
func (UnimplementedAlertDefsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAlertDefsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertDefsServiceServer will
// result in compilation errors.
type UnsafeAlertDefsServiceServer interface {
	mustEmbedUnimplementedAlertDefsServiceServer()
}

func RegisterAlertDefsServiceServer(s grpc.ServiceRegistrar, srv AlertDefsServiceServer) {
	// If the following call panics, it indicates UnimplementedAlertDefsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertDefsService_ServiceDesc, srv)
}

func _AlertDefsService_ListAlertDefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertDefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertDefsServiceServer).ListAlertDefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertDefsService_ListAlertDefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertDefsServiceServer).ListAlertDefs(ctx, req.(*ListAlertDefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertDefsService_GetAlertDef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertDefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertDefsServiceServer).GetAlertDef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertDefsService_GetAlertDef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertDefsServiceServer).GetAlertDef(ctx, req.(*GetAlertDefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertDefsService_ServiceDesc is the grpc.ServiceDesc for AlertDefsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertDefsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.coralogixapis.alerts.v3.AlertDefsService",
	HandlerType: (*AlertDefsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlertDefs",
			Handler:    _AlertDefsService_ListAlertDefs_Handler,
		},
		{
			MethodName: "GetAlertDef",
			Handler:    _AlertDefsService_GetAlertDef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alerts.proto",
}
