package models

// Region represents a Coralogix deployment region.
type Region struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Endpoint string `json:"endpoint"`
}

// Regions maps region IDs to their gRPC endpoints.
var Regions = map[string]Region{
	"eu1": {ID: "eu1", Name: "Europe 1", Endpoint: "api.coralogix.com:443"},
	"eu2": {ID: "eu2", Name: "Europe 2", Endpoint: "api.eu2.coralogix.com:443"},
	"us1": {ID: "us1", Name: "US 1", Endpoint: "api.coralogix.us:443"},
	"us2": {ID: "us2", Name: "US 2", Endpoint: "api.cx498.coralogix.com:443"},
	"ap1": {ID: "ap1", Name: "Asia Pacific 1 (India)", Endpoint: "api.app.coralogix.in:443"},
	"ap2": {ID: "ap2", Name: "Asia Pacific 2 (Singapore)", Endpoint: "api.coralogixsg.com:443"},
	"ap3": {ID: "ap3", Name: "Asia Pacific 3", Endpoint: "api.ap3.coralogix.com:443"},
}

// AlertDef represents a parsed Coralogix alert definition.
type AlertDef struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Enabled     bool              `json:"enabled"`
	Priority    string            `json:"priority"`
	AlertType   string            `json:"alert_type"`
	TypeDef     map[string]any    `json:"type_definition"`
	GroupByKeys []string          `json:"group_by_keys"`
	Labels      map[string]string `json:"entity_labels"`
	Features    AlertFeatures     `json:"features"`
}

// AlertFeatures are extracted dimensions used for similarity and MITRE mapping.
type AlertFeatures struct {
	DataSources    []string `json:"data_sources"`
	Entities       []string `json:"entities"`
	Actions        []string `json:"actions"`
	Conditions     []string `json:"conditions"`
	TimeWindow     string   `json:"time_window"`
	Techniques     []string `json:"techniques"`
	Tactics        []string `json:"tactics"`
	BuildingBlocks  []string `json:"building_blocks,omitempty"`
	IsBuildingBlock bool     `json:"is_building_block,omitempty"`
	VendorCovered   bool     `json:"vendor_covered,omitempty"`
	VendorName     string   `json:"vendor_name,omitempty"`
	IsSecurityAlert bool    `json:"is_security_alert"`
}

// TechniqueCoverageEntry holds per-technique alert coverage for the signals pipeline.
// Weak is true when the technique is covered but all covering alerts are unscoped
// (no DataSources and no Entities), making detection quality poor.
type TechniqueCoverageEntry struct {
	Name       string `json:"name"`
	Tactic     string `json:"tactic"`
	AlertCount int    `json:"alert_count"`
	Weak       bool   `json:"weak,omitempty"`
}

// GapCategories holds the 6-category LLM gap analysis output.
type GapCategories struct {
	EnvironmentCleanup   []string `json:"environment_cleanup"`
	NoDetection          []string `json:"no_detection"`
	PoorTacticCoverage   []string `json:"poor_tactic_coverage"`
	WeakDetectionQuality []string `json:"weak_detection_quality"`
	AdvancedUseCases     []string `json:"advanced_use_cases"`
	MissingSourceAlerts  []string `json:"missing_source_alerts"`
}

// ActionableRecommendation is a structured, actionable gap item generated by
// EnrichActionable — prose description plus severity, log source, and Lucene query.
type ActionableRecommendation struct {
	Prose         string `json:"prose"`
	LogSource     string `json:"log_source"`
	Severity      string `json:"severity"`
	QuerySkeleton string `json:"query_skeleton"`
}

// ActionableGapCategories holds structured recommendations for the four gap
// categories where a Lucene query skeleton can be grounded in the client's integrations.
type ActionableGapCategories struct {
	NoDetection          []ActionableRecommendation `json:"no_detection"`
	WeakDetectionQuality []ActionableRecommendation `json:"weak_detection_quality"`
	MissingSourceAlerts  []ActionableRecommendation `json:"missing_source_alerts"`
	AdvancedUseCases     []ActionableRecommendation `json:"advanced_use_cases"`
}

type ExportNarrativeReport struct {
	ExecutiveSummary   string   `json:"executive_summary"`
	KeyFindings        []string `json:"key_findings"`
	RecommendedActions []string `json:"recommended_actions"`
}

// MITRECoverageResult is the response for MITRE coverage analysis.
type MITRECoverageResult struct {
	NavigatorLayer    map[string]any                    `json:"navigator_layer"`
	Summary           MITRECoverageSummary              `json:"summary"`
	TechniqueCoverage map[string]TechniqueCoverageEntry `json:"technique_coverage,omitempty"`
}

type MITRECoverageSummary struct {
	TotalTechniques      int                       `json:"total_techniques"`
	CoveredTechniques    int                       `json:"covered_techniques"`
	CoveragePercent      float64                   `json:"coverage_percent"`
	TotalSubTechniques   int                       `json:"total_sub_techniques"`
	CoveredSubTechniques int                       `json:"covered_sub_techniques"`
	TacticBreakdown      map[string]TacticCoverage `json:"tactic_breakdown"`
}

type TacticCoverage struct {
	TacticName  string  `json:"tactic_name"`
	Total       int     `json:"total"`
	Covered     int     `json:"covered"`
	Percent     float64 `json:"percent"`
	TotalSubs   int     `json:"total_subs"`
	CoveredSubs int     `json:"covered_subs"`
}

// NoiseAlert represents an alert flagged by the hybrid noise model.
// TriggerCount is 0 when behavioral data is unavailable or the alert is not behaviorally noisy.
// NoiseType is "behavioral", "structural", or "both"; empty string means unclassified.
type NoiseAlert struct {
	Name            string   `json:"name"`
	MissingFeatures []string `json:"missing_features"`
	Reason          string   `json:"reason,omitempty"`
	TriggerCount    int      `json:"trigger_count,omitempty"`
	NoiseType       string   `json:"noise_type,omitempty"`
}

// NoiseRequest is the request body for POST /api/noise.
type NoiseRequest struct {
	Client       string `json:"client"`
	LookbackDays int    `json:"lookback_days"`
}

// NoiseResponse is the response for POST /api/noise.
type NoiseResponse struct {
	NoiseAlerts  []NoiseAlert `json:"noise_alerts"`
	LookbackDays int `json:"lookback_days"`
}

// SimilarityResult is the response for alert insight analysis.
type SimilarityResult struct {
	Families         []DetectionFamily `json:"families"`
	Duplicates       []DuplicateGroup  `json:"duplicates"`
	MergeSuggestions []MergeSuggestion `json:"merge_suggestions"`
	UniqueDetections []string          `json:"unique_detections"`
	NoiseAlerts      []NoiseAlert      `json:"noise_alerts"`
}

type DetectionFamily struct {
	Name    string   `json:"name"`
	AlertIDs []string `json:"alert_ids"`
	AlertNames []string `json:"alert_names"`
}

type DuplicateGroup struct {
	AlertIDs    []string `json:"alert_ids"`
	AlertNames  []string `json:"alert_names"`
	Similarity  float64  `json:"similarity"`
	Explanation string   `json:"explanation"`
}

type MergeSuggestion struct {
	AlertIDs    []string `json:"alert_ids"`
	AlertNames  []string `json:"alert_names"`
	Reason      string   `json:"reason"`
}

// InsightsReport is the LLM-generated analyst report for a SimilarityResult.
type InsightsReport struct {
	Model                        string                   `json:"model,omitempty"`
	Summary                      string                   `json:"summary"`
	TopPriority                  []string                 `json:"top_priority"`
	Strengths                    []string                 `json:"strengths"`
	Recommendations              []string                 `json:"recommendations"`
	EnrichedDups                 []string                 `json:"enriched_dups"`
	GapCategories                GapCategories            `json:"gap_categories"`
	ActionableGaps               *ActionableGapCategories `json:"actionable_gaps,omitempty"`
	NoiseExplanations            []string                 `json:"noise_explanations"`
	AllIntegrationsVendorManaged bool                     `json:"all_integrations_vendor_managed,omitempty"`
}

type PairComparison struct {
	AlertA      string  `json:"alert_a"`
	AlertB      string  `json:"alert_b"`
	NameA       string  `json:"name_a"`
	NameB       string  `json:"name_b"`
	Similarity  float64 `json:"similarity"`
	Explanation string  `json:"explanation"`
}

// API request/response types.
type ClientAnalyzeRequest struct {
	Client       string `json:"client"`
	LookbackDays int    `json:"lookback_days"`
}

type AnalyzeResponse struct {
	Integrations   []IntegrationInfo    `json:"integrations"`
	Stats          AnalysisStats        `json:"stats"`
	MITRECoverage  *MITRECoverageResult `json:"mitre_coverage"`
	AlertInsights  *SimilarityResult    `json:"alert_insights"`
	InsightsReport *InsightsReport      `json:"insights_report,omitempty"`
	Cached         bool                 `json:"cached"`
}

type IntegrationInfo struct {
	Name               string `json:"name"`
	Application        string `json:"application"`
	Subsystem          string `json:"subsystem"`
	AlertCount         int    `json:"alert_count"`
	VendorCoveredCount int    `json:"vendor_covered_count,omitempty"`
}

type AnalysisStats struct {
	TotalIntegrations      int `json:"total_integrations"`
	DoneIntegrations       int `json:"done_integrations"`
	TotalAlerts            int `json:"total_alerts"`
	SecurityAlerts         int `json:"security_alerts"`
	VendorCoveredAlerts    int `json:"vendor_covered_alerts"`
	IntegrationsWithAlerts int `json:"integrations_with_alerts"`
}

// SuggestionsRequest is the request body for per-technique alert suggestions.
type SuggestionsRequest struct {
	Client      string `json:"client"`
	Provider    string `json:"provider"`     // "claude" or "nvidia"; empty = default
	TechniqueID string `json:"technique_id"` // e.g. "T1059"
	Tactic      string `json:"tactic"`       // e.g. "execution"
	Force       bool   `json:"force"`        // if true, bypass cache and append a new generation
}

// SuggestionsResponse wraps LLM-generated alert suggestions for one technique.
type SuggestionsResponse struct {
	Provider      string            `json:"provider"`
	TechniqueID   string            `json:"technique_id"`
	TechniqueName string            `json:"technique_name"`
	Suggestions   []AlertSuggestion `json:"suggestions"`
	LogSources    []string          `json:"log_sources"`
}

// AlertSuggestion is a single LLM-generated alert recommendation.
type AlertSuggestion struct {
	LogSource   string `json:"log_source"`
	AlertName   string `json:"alert_name"`
	Description string `json:"description"`
	QueryHint   string `json:"query_hint"`
	Priority    string `json:"priority"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}
